// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5iDtaW6-Eg5HPGsHf6ZstPFefjkfA1OE',
    appId: '1:960137440339:web:d73c6830ff236ffcf5aaa6',
    messagingSenderId: '960137440339',
    projectId: 'steeve-1998-554a8',
    authDomain: 'steeve-1998-554a8.firebaseapp.com',
    storageBucket: 'steeve-1998-554a8.firebasestorage.app',
    measurementId: 'G-NXK01BVTC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo3EO1AXmkiwXYU_eD59_AsnU6PUqiSBY',
    appId: '1:960137440339:android:88f42f3b48e434a3f5aaa6',
    messagingSenderId: '960137440339',
    projectId: 'steeve-1998-554a8',
    storageBucket: 'steeve-1998-554a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPsvoIF1l2zLtYeFSkBk6tNVqRUB4Abgk',
    appId: '1:960137440339:ios:d38fe2b7eaca28dcf5aaa6',
    messagingSenderId: '960137440339',
    projectId: 'steeve-1998-554a8',
    storageBucket: 'steeve-1998-554a8.firebasestorage.app',
    iosBundleId: 'com.example.projetFlutterFindYourMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPsvoIF1l2zLtYeFSkBk6tNVqRUB4Abgk',
    appId: '1:960137440339:ios:d38fe2b7eaca28dcf5aaa6',
    messagingSenderId: '960137440339',
    projectId: 'steeve-1998-554a8',
    storageBucket: 'steeve-1998-554a8.firebasestorage.app',
    iosBundleId: 'com.example.projetFlutterFindYourMovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5iDtaW6-Eg5HPGsHf6ZstPFefjkfA1OE',
    appId: '1:960137440339:web:f6acb5eb8ef23fd0f5aaa6',
    messagingSenderId: '960137440339',
    projectId: 'steeve-1998-554a8',
    authDomain: 'steeve-1998-554a8.firebaseapp.com',
    storageBucket: 'steeve-1998-554a8.firebasestorage.app',
    measurementId: 'G-29WCR7KFRQ',
  );
}
